baseURL = "https://nguyenmphu.github.io"
languageCode = "en-us"
title = "nguyenmphu's notes"
theme = "noteworthy"
paginate = 10
showReadMore = true

googleAnalytics = "G-DRQJ044QLT"

# Social
linkedin = "nguyenmphu"
github = "nguyenmphu"

[taxonomies]
  tag = "tags"
  category = "categories"
